# Generated by Django 5.1.1 on 2024-10-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={},
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_measure', to='measurement.sensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
