# Generated by Django 5.1.1 on 2024-10-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
